# Generated by Django 6.0.3 on 2026-03-19 18:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_termino', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('tom_original', models.CharField(max_length=10)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('compasso', models.CharField(blank=True, max_length=10, null=True)),
                ('link_referencia', models.URLField(blank=True, null=True)),
                ('cifra_pdf', models.FileField(blank=True, null=True, upload_to='cifras_pdf/')),
                ('cifra_texto', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Separe as tags por vírgula. Ex: Adoração, Ceia', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('funcao_principal', models.CharField(max_length=50)),
                ('funcoes_secundarias', models.TextField(blank=True, help_text='Ex: Violão, Teclado', null=True)),
                ('nivel_acesso', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Líder de Louvor'), (3, 'Membro')], default=3)),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para inativar o membro em vez de deletar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_confirmacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20)),
                ('culto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='api.culto')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_escalas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSetlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('tom_execucao', models.CharField(max_length=10)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('culto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='api.culto')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.musica')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
