# Generated by Django 6.0.3 on 2026-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registrologin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='link_referencia',
        ),
        migrations.AddField(
            model_name='musica',
            name='link_audio',
            field=models.URLField(blank=True, help_text='Spotify, Deezer, Apple Music', null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='link_cifra',
            field=models.URLField(blank=True, help_text='CifraClub, etc', null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='link_letra',
            field=models.URLField(blank=True, help_text='Letras.com, Vagalume, etc', null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='link_youtube',
            field=models.URLField(blank=True, help_text='Link do YouTube', null=True),
        ),
    ]
