# Generated by Django 6.0.3 on 2026-04-01 19:27

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_musica_cover_url_musica_genius_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('configuracoes', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ministerio',
                'verbose_name_plural': 'Ministerios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='invite_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_global_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConviteMinisterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nome_convidado', models.CharField(blank=True, max_length=150, null=True)),
                ('nivel_acesso', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Lider de Louvor'), (3, 'Membro')], default=3)),
                ('token', models.CharField(default=api.models.generate_invite_token, max_length=128, unique=True)),
                ('access_code', models.CharField(default=api.models.generate_access_code, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('REVOGADO', 'Revogado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=20)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_aceitos', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_enviados', to=settings.AUTH_USER_MODEL)),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='api.ministerio')),
            ],
            options={
                'verbose_name': 'Convite de Ministerio',
                'verbose_name_plural': 'Convites de Ministerio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='culto',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultos', to='api.ministerio'),
        ),
        migrations.AddField(
            model_name='escala',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='api.ministerio'),
        ),
        migrations.AddField(
            model_name='itemsetlist',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='api.ministerio'),
        ),
        migrations.AddField(
            model_name='musica',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='api.ministerio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.ministerio'),
        ),
    ]
