# Generated by Django 6.0.3 on 2026-04-07 23:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_backfill_ministerios_igreja'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoIgrejaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_institucional', models.CharField(choices=[('MEMBRO', 'Membro')], default='MEMBRO', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuarios', to='api.igreja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_igreja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vinculo Igreja Usuario',
                'verbose_name_plural': 'Vinculos Igreja Usuario',
                'ordering': ['-is_active', '-joined_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'igreja'), name='unique_vinculo_igreja_usuario')],
            },
        ),
        migrations.CreateModel(
            name='VinculoMinisterioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_no_ministerio', models.CharField(choices=[('MEMBRO', 'Membro')], default='MEMBRO', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuarios', to='api.ministerio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_ministerio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vinculo Ministerio Usuario',
                'verbose_name_plural': 'Vinculos Ministerio Usuario',
                'ordering': ['-is_primary', '-is_active', '-joined_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'ministerio'), name='unique_vinculo_ministerio_usuario')],
            },
        ),
    ]
