# Generated by Django 6.0.3 on 2026-04-08 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_backfill_vinculos_ministerio_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('chave', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('configuracoes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IgrejaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('configuracoes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_habilitados', to='api.igreja')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igrejas_habilitadas', to='api.modulo')),
            ],
            options={
                'verbose_name': 'Igreja Modulo',
                'verbose_name_plural': 'Igrejas Modulos',
                'ordering': ['igreja__nome', 'modulo__nome'],
                'constraints': [models.UniqueConstraint(fields=('igreja', 'modulo'), name='unique_igreja_modulo')],
            },
        ),
    ]
