# Generated by Django 6.0.3 on 2026-04-08 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_backfill_eventos_from_cultos'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.SlugField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='escopo',
            field=models.CharField(default='platform', max_length=20),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='api.igreja'),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='api.ministerio'),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='modulo',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='escala',
            index=models.Index(fields=['ministerio', 'status_confirmacao'], name='api_escala_ministe_9ad890_idx'),
        ),
        migrations.AddIndex(
            model_name='escala',
            index=models.Index(fields=['culto', 'membro'], name='api_escala_culto_i_e61dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['igreja', 'status', 'data'], name='api_evento_igreja__4de63a_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['ministerio', 'status', 'data'], name='api_evento_ministe_500388_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['source_module', 'status'], name='api_evento_source__a4eea7_idx'),
        ),
        migrations.AddIndex(
            model_name='culto',
            index=models.Index(fields=['ministerio', 'status', 'data'], name='api_culto_ministe_f80b56_idx'),
        ),
        migrations.AddIndex(
            model_name='igrejamodulo',
            index=models.Index(fields=['igreja', 'is_enabled'], name='api_igrejam_igreja__d1bcc8_idx'),
        ),
        migrations.AddIndex(
            model_name='igrejamodulo',
            index=models.Index(fields=['modulo', 'is_enabled'], name='api_igrejam_modulo__064419_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsetlist',
            index=models.Index(fields=['ministerio', 'culto', 'ordem'], name='api_itemset_ministe_052326_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['escopo', 'data_hora'], name='api_logaudi_escopo_5f3e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['igreja', 'data_hora'], name='api_logaudi_igreja__eeee47_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['ministerio', 'data_hora'], name='api_logaudi_ministe_124199_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['modulo', 'data_hora'], name='api_logaudi_modulo_aea77c_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['acao', 'data_hora'], name='api_logaudi_acao_f59d92_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', 'data_hora'], name='api_logaudi_usuario_09a8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='musica',
            index=models.Index(fields=['is_active', 'classificacao'], name='api_musica_is_acti_7917e8_idx'),
        ),
        migrations.AddIndex(
            model_name='musica',
            index=models.Index(fields=['artista', 'titulo'], name='api_musica_artista_e8033b_idx'),
        ),
        migrations.AddIndex(
            model_name='musica',
            index=models.Index(fields=['metadata_last_synced_at'], name='api_musica_metadat_24cb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='registrologin',
            index=models.Index(fields=['usuario', 'data_hora'], name='api_registr_usuario_42c2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['ministerio', 'is_active'], name='api_usuario_ministe_c17344_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_global_admin', 'is_active'], name='api_usuario_is_glob_840fef_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['nivel_acesso', 'is_active'], name='api_usuario_nivel_a_400d22_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculoigrejausuario',
            index=models.Index(fields=['usuario', 'is_active'], name='api_vinculo_usuario_b0ccb2_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculoigrejausuario',
            index=models.Index(fields=['igreja', 'is_active'], name='api_vinculo_igreja__0e6669_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculoministeriousuario',
            index=models.Index(fields=['usuario', 'is_active', 'is_primary'], name='api_vinculo_usuario_70e50a_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculoministeriousuario',
            index=models.Index(fields=['ministerio', 'is_active'], name='api_vinculo_ministe_15f614_idx'),
        ),
        migrations.AddField(
            model_name='apirequesterrorlog',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_error_logs', to='api.igreja'),
        ),
        migrations.AddField(
            model_name='apirequesterrorlog',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_error_logs', to='api.ministerio'),
        ),
        migrations.AddField(
            model_name='apirequesterrorlog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apirequesterrorlog',
            index=models.Index(fields=['status_code', 'occurred_at'], name='api_apirequ_status__3adfa2_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequesterrorlog',
            index=models.Index(fields=['path', 'occurred_at'], name='api_apirequ_path_f5eb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequesterrorlog',
            index=models.Index(fields=['igreja', 'occurred_at'], name='api_apirequ_igreja__a63d03_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequesterrorlog',
            index=models.Index(fields=['ministerio', 'occurred_at'], name='api_apirequ_ministe_a08deb_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequesterrorlog',
            index=models.Index(fields=['modulo', 'occurred_at'], name='api_apirequ_modulo_4302aa_idx'),
        ),
    ]
