# Generated by Django 6.0.3 on 2026-04-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_migrate_usuario_to_accounts'),
        ('api', '0022_seed_events_module_catalog'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='usuario',
                    name='api_usuario_ministe_c17344_idx',
                ),
                migrations.RemoveIndex(
                    model_name='usuario',
                    name='api_usuario_is_glob_840fef_idx',
                ),
                migrations.RemoveIndex(
                    model_name='usuario',
                    name='api_usuario_nivel_a_400d22_idx',
                ),
                migrations.DeleteModel(
                    name='Usuario',
                ),
            ],
            database_operations=[],
        ),
    ]
