# Generated by Django 6.0.3 on 2026-04-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_usuario_api_usuario_ministe_c17344_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="vinculoministeriousuario",
            name="api_vinculo_usuario_70e50a_idx",
        ),
        migrations.RenameIndex(
            model_name="vinculoigrejausuario",
            new_name="idx_vig_user_active",
            old_name="api_vinculo_usuario_b0ccb2_idx",
        ),
        migrations.RenameIndex(
            model_name="vinculoigrejausuario",
            new_name="idx_vig_igreja_active",
            old_name="api_vinculo_igreja__0e6669_idx",
        ),
        migrations.RenameIndex(
            model_name="vinculoministeriousuario",
            new_name="idx_vmin_min_active",
            old_name="api_vinculo_ministe_15f614_idx",
        ),
        migrations.AddIndex(
            model_name="ministerio",
            index=models.Index(fields=["nome", "is_active"], name="idx_minist_nome_active"),
        ),
        migrations.AddIndex(
            model_name="musica",
            index=models.Index(fields=["titulo"], name="idx_musica_titulo"),
        ),
        migrations.AddIndex(
            model_name="musica",
            index=models.Index(fields=["ministerio", "is_active"], name="idx_musica_min_active"),
        ),
        migrations.AddIndex(
            model_name="vinculoministeriousuario",
            index=models.Index(fields=["usuario", "is_active"], name="idx_vmin_user_active"),
        ),
    ]
