# Generated by Django 6.0.3 on 2026-04-16 11:40

import django.db.models.deletion
import institutions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_performance_indexes'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Log de Auditoria', 'verbose_name_plural': 'Logs de Auditoria'},
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='instance_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='instance_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'Criacao'), ('UPDATE', 'Atualizacao'), ('DELETE', 'Exclusao')], max_length=100),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='escopo',
            field=models.CharField(blank=True, default='platform', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='modelo_afetado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='access_code',
            field=models.CharField(db_index=True, default=institutions.models.generate_access_code, help_text='Codigo unico para acesso/convite ao ministerio', max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['instance_content_type', 'instance_id'], name='api_logaudi_instanc_5ed21f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ministerio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('access_code',), name='unique_active_ministerio_access_code'),
        ),
        migrations.AlterModelTable(
            name='logauditoria',
            table='api_logauditoria',
        ),
        migrations.AlterModelTable(
            name='ministerio',
            table='api_ministerio',
        ),
    ]
