# Generated by Django 6.0.3 on 2026-04-15 14:16

import accounts.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0022_seed_events_module_catalog'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Usuario',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('password', models.CharField(max_length=128, verbose_name='password')),
                        ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                        ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                        ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                        ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                        ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                        ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                        ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                        ('email', models.EmailField(max_length=254, unique=True)),
                        ('telefone', models.CharField(blank=True, max_length=20)),
                        ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                        ('funcao_principal', models.CharField(blank=True, default='', max_length=100)),
                        ('funcoes_secundarias', models.TextField(blank=True, help_text='Ex: Violao, Teclado', null=True)),
                        ('funcoes', models.JSONField(blank=True, default=list)),
                        ('nivel_acesso', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Lider de Louvor'), (3, 'Membro')], default=3)),
                        ('is_global_admin', models.BooleanField(default=False)),
                        ('invite_accepted_at', models.DateTimeField(blank=True, null=True)),
                        ('access_code', models.CharField(blank=True, max_length=100, null=True)),
                        ('is_active', models.BooleanField(default=True, help_text='Desmarque para inativar o membro em vez de deletar')),
                        ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                        ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                    ],
                    options={
                        'verbose_name': 'user',
                        'verbose_name_plural': 'users',
                        'db_table': 'api_usuario',
                        'abstract': False,
                        'indexes': [models.Index(fields=['is_global_admin', 'is_active'], name='api_usuario_is_glob_840fef_idx'), models.Index(fields=['nivel_acesso', 'is_active'], name='api_usuario_nivel_a_400d22_idx')],
                    },
                    managers=[
                        ('objects', accounts.models.UsuarioManager()),
                    ],
                ),
            ],
            database_operations=[],
        ),
    ]
