# Generated by Django 6.0.3 on 2026-04-15 18:48

from django.db import migrations


def drop_legacy_ministerio_fk_column(apps, schema_editor):
    table_name = "api_usuario"

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }

    if "ministerio_id" not in columns:
        return

    vendor = schema_editor.connection.vendor

    if vendor == "postgresql":
        schema_editor.execute(
            'ALTER TABLE "api_usuario" DROP CONSTRAINT IF EXISTS "api_usuario_ministerio_id_ebf94ec4_fk_api_ministerio_id"'
        )
        schema_editor.execute('DROP INDEX IF EXISTS "api_usuario_ministe_c17344_idx"')
        schema_editor.execute('DROP INDEX IF EXISTS "api_usuario_ministerio_id_ebf94ec4"')
        schema_editor.execute('ALTER TABLE "api_usuario" DROP COLUMN IF EXISTS "ministerio_id"')
        return

    if vendor == "sqlite":
        schema_editor.execute('DROP INDEX IF EXISTS "api_usuario_ministe_c17344_idx"')
        schema_editor.execute('DROP INDEX IF EXISTS "api_usuario_ministerio_id_ebf94ec4"')
        schema_editor.execute('ALTER TABLE "api_usuario" DROP COLUMN "ministerio_id"')
        return

    schema_editor.execute('ALTER TABLE "api_usuario" DROP COLUMN "ministerio_id"')


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_migrate_usuario_ministerio_to_vinculo"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_legacy_ministerio_fk_column, migrations.RunPython.noop),
            ],
            state_operations=[],
        ),
    ]
