# Generated by Django 6.0.3 on 2026-04-15 18:50

from django.db import migrations


def add_missing_access_code_column(apps, schema_editor):
    table_name = "api_usuario"

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }

    if "access_code" in columns:
        return

    schema_editor.execute('ALTER TABLE "api_usuario" ADD COLUMN "access_code" varchar(100) NULL')


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_ministerio_fk_field"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_missing_access_code_column, migrations.RunPython.noop),
            ],
            state_operations=[],
        ),
    ]
