# Generated by Django 6.0.3 on 2026-04-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sync_usuario_access_code_column'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['nivel_acesso'], name='idx_usuario_nivel'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active'], name='idx_usuario_ativo'),
        ),
    ]
