# Generated by Django 6.0.3 on 2026-04-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ministerio_access_code_and_global_music_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerio',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ministerio',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('louvor', 'Louvor'), ('adoracao', 'Adoracao'), ('contemplacao', 'Contemplacao'), ('consagracao', 'Consagracao'), ('alegria', 'Alegria (Jubilo)'), ('especiais', 'Especiais')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='funcoes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao_principal',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.ministerio')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
