# Generated by Django 6.0.3 on 2026-03-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_logauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='genius_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='genius_popularidade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='isrc',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='metadata_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='metadata_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='spotify_popularidade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'Criacao'), ('UPDATE', 'Atualizacao'), ('DELETE', 'Exclusao')], max_length=10),
        ),
        migrations.AlterField(
            model_name='musica',
            name='link_letra',
            field=models.URLField(blank=True, help_text='Link oficial para letra/licenca de referencia', null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='tags',
            field=models.CharField(blank=True, help_text='Separe as tags por virgula. Ex: Adoracao, Ceia', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcoes_secundarias',
            field=models.TextField(blank=True, help_text='Ex: Violao, Teclado', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Lider de Louvor'), (3, 'Membro')], default=3),
        ),
        migrations.CreateModel(
            name='MusicMetadataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('cache_key', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'cache_key'], name='api_musicme_provide_8618ad_idx'), models.Index(fields=['expires_at'], name='api_musicme_expires_bd7373_idx')],
                'unique_together': {('provider', 'cache_key')},
            },
        ),
    ]
