# Generated by Django 6.0.3 on 2026-04-15 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0023_remove_usuario_api_usuario_ministe_c17344_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_codename', models.CharField(choices=[('music.add_musica', 'Criar Musica'), ('music.change_musica', 'Editar Musica'), ('music.delete_musica', 'Excluir Musica'), ('events.add_culto', 'Criar Culto'), ('events.change_culto', 'Editar Culto'), ('events.delete_culto', 'Excluir Culto')], max_length=100)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('igreja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='api.igreja')),
                ('ministerio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='api.ministerio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_userpermissiongrant',
                'indexes': [models.Index(fields=['usuario', 'is_active'], name='system_user_usuario_c358ee_idx')],
                'unique_together': {('usuario', 'permission_codename', 'igreja', 'ministerio')},
            },
        ),
    ]
