# Generated by Django 6.0.3 on 2026-04-15 20:12

from django.db import migrations


def update_logauditoria_schema(apps, schema_editor):
    table_name = "api_logauditoria"
    vendor = schema_editor.connection.vendor

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }

    if "instance_content_type_id" not in columns:
        schema_editor.execute(
            'ALTER TABLE "api_logauditoria" ADD COLUMN "instance_content_type_id" bigint NULL'
        )

    if "instance_id" not in columns:
        schema_editor.execute(
            'ALTER TABLE "api_logauditoria" ADD COLUMN "instance_id" integer NULL'
        )

    if "metadata" not in columns:
        if vendor == "postgresql":
            schema_editor.execute(
                'ALTER TABLE "api_logauditoria" ADD COLUMN "metadata" jsonb NOT NULL DEFAULT \'{}\'::jsonb'
            )
        else:
            schema_editor.execute(
                'ALTER TABLE "api_logauditoria" ADD COLUMN "metadata" text NOT NULL DEFAULT \'{}\''
            )

    if vendor == "postgresql":
        schema_editor.execute(
            'ALTER TABLE "api_logauditoria" ALTER COLUMN "acao" TYPE varchar(100)'
        )
        schema_editor.execute(
            'ALTER TABLE "api_logauditoria" ALTER COLUMN "modelo_afetado" TYPE varchar(100)'
        )
        schema_editor.execute(
            'ALTER TABLE "api_logauditoria" ALTER COLUMN "descricao" TYPE text'
        )
        schema_editor.execute(
            'ALTER TABLE "api_logauditoria" ALTER COLUMN "escopo" TYPE varchar(50)'
        )
        schema_editor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'api_logauditoria_instance_content_type_id_fk'
                ) THEN
                    ALTER TABLE "api_logauditoria"
                    ADD CONSTRAINT "api_logauditoria_instance_content_type_id_fk"
                    FOREIGN KEY ("instance_content_type_id")
                    REFERENCES "django_content_type" ("id")
                    DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END
            $$;
            """
        )
        schema_editor.execute(
            'CREATE INDEX IF NOT EXISTS "api_logauditoria_instanc_ct_obj_idx" ON "api_logauditoria" ("instance_content_type_id", "instance_id")'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("system", "0001_add_user_permission_grant_model"),
    ]

    operations = [
        migrations.RunPython(update_logauditoria_schema, migrations.RunPython.noop),
    ]
